services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodb"
    volumes:
      - dynamodb-data:/home/dynamodb

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    volumes:
      - rustfs-data:/data

  rustfs-init:
    image: minio/mc
    depends_on:
      - rustfs
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local-storage http://rustfs:9000 rustfsadmin rustfsadmin;
      mc mb local-storage/sulfurbook --ignore-existing;
      "

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: soketi
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - SOKETI_DEBUG=1
      - SOKETI_METRICS_ENABLED=1
      - SOKETI_DEFAULT_APP_ID=app-id
      - SOKETI_DEFAULT_APP_KEY=app-key
      - SOKETI_DEFAULT_APP_SECRET=app-secret

  postgres:
    image: postgres:16-alpine
    container_name: ledger-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sulfur_ledger
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dynamodb-data:
  rustfs-data:
  postgres-data:
